services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chontak_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/dat
volumes:
  pgdata:
